name: xidranreb
version: 1.5.17
summary: Money Manager Ex - simple to use financial management software
description: |
  Money Manager Ex (MMEX) is a free, open-source, cross-platform,
  easy-to-use personal finance software. It primarily helps organize
  one's finances and keeps track of where, when and how the money goes.
  MMEX includes all the basic features that 90% of users would want to
  see in a personal finance application. The design goals are to
  concentrate on simplicity and user friendliness - something one can
  use everyday.
icon: ./resources/mmex.svg
base: core20
confinement: strict
grade: stable

apps:
  mmex:
    command: bin/mmex
    desktop: share/applications/mmex.desktop
    extensions: [gnome-3-38]
    plugs:
    - x11
    - wayland
    - unity7
    - desktop
    - desktop-legacy
    - home
    - network
    - network-bind
    - opengl
    - pulseaudio
    - removable-media
    - process-control 
    - mount-observe

parts:
  wxwidget:
    plugin: autotools    
    source: https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.0/wxWidgets-3.2.0.tar.bz2
    source-type: tar

    build-packages:
      # - cmake 
      # - checkinstall
      # - build-essential
      # - ccache
      - libwebkit2gtk-4.0-dev
      - liblua5.3-dev
      - libcurl4-openssl-dev
      - libgtk2.0-dev

      - gettext
      - libcairo2-dev
      - libexpat1-dev
      - libgtk-3-dev
      - libjpeg-dev
      - libnotify-dev
      - libpng-dev
      - libsecret-1-dev
      - libtiff5-dev
      - libxtst-dev
      - zlib1g-dev
    override-build: |
      set -eu

      ./configure \
        --disable-shared \
        --prefix="${SNAPCRAFT_STAGE}" \
        --enable-cxx11 \
        --with-cxx=11 \
        --without-libtiff \
        --enable-webview  \
        --with-gtk=3 \
        --enable-unicode \
        --enable-intl 

      make \
        --jobs=$(nproc)
      make prefix="${SNAPCRAFT_PART_INSTALL}" install

    stage-packages:
      # For addr2line, required by wxWidgets error dialog
      - binutils  
    
    filesets:
      autoconf-macros:
        - share/aclocal/*
      bakefiles:
        - share/bakefile/*
      files-from-stage-packages:
        - usr/*
      executables:
        - bin/*
      headers:
        - include/*
      libraries:
        - lib/*
      localizations:
        - share/locale/*
    stage:
      - $autoconf-macros
      - $executables
      - $files-from-stage-packages
      - $headers
      - $libraries
      - $localizations
    override-stage: |
      set -eu
      snapcraftctl stage
      # Fixup wrong wx-config link
      ln \
        --force \
        --relative \
        --symbolic \
        "${SNAPCRAFT_STAGE}"/lib/wx/config/gtk3-unicode-static-3.2 \
        "${SNAPCRAFT_STAGE}"/bin/wx-config
    prime:
      - $files-from-stage-packages
      - $localizations

  mmex:
    plugin: cmake
    source: .
    source-type: local
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release

    override-build: |
      cd ${SNAPCRAFT_PART_SRC}
      cmake . -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${SNAPCRAFT_PART_INSTALL}"
      cmake --build . --target install
  
#      cd build/bakefiles
#      bakefile_gen
#      cd ../../auxd
#      bakefilize -c -v
#      cd ..
#      aclocal -I m4 -I $SNAPCRAFT_STAGE/share/aclocal
#      autoconf
#      snapcraftctl build
#    after: [desktop-gtk2, bakefile]
    after:
      - wxwidget
    build-packages:
      - git
      - gettext
      - lsb-release
      - checkinstall
      - build-essential
      - ccache
#      - libwxgtk-webview3.0-gtk3-dev
      - libwebkit2gtk-4.0-dev
      - liblua5.3-dev
      - libcurl4-openssl-dev
      - libgtk2.0-dev

    stage-packages:
      - libcanberra-gtk3-module
      - libcanberra-gtk-module

      - libasn1-8-heimdal
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libcurl4
      - libdatrie1
      - libdrm2
      - libegl1
      - libenchant-2-2
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgssapi3-heimdal
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgudev-1.0-0
      - libharfbuzz-icu0
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libhyphen0
      - libice6
      - libicu66
      - libjavascriptcoregtk-4.0-18
      - libjpeg-turbo8
      - libkrb5-26-heimdal
      - liblcms2-2
      - libldap-2.4-2
      - liblua5.3-0
      - libnghttp2-14
      - libnotify4
      - libopenjp2-7
      - liborc-0.4-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsecret-1-0
      - libsm6
      - libsoup2.4-1
      - libssh-4
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libwebkit2gtk-4.0-37
      - libwebp6
      - libwebpdemux2
      - libwind0-heimdal
      - libwoff1
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxslt1.1

    filesets:
      executables:
        - bin/*
      files-in-stage-packages:
        - usr/*
      freedesktop-desktop-entries:
        - share/applications/*
      icons:
        - share/icons/*
      localizations:
        - share/locale/*
      manpages:
        - share/man/*
      pixmaps:
        - share/pixmaps/*
      resources:
        - share/*

    stage:
      - $executables
      - $files-in-stage-packages
      - $freedesktop-desktop-entries
      - $manpages
      - $localizations
      - $pixmaps
      - $resources

    prime:
      - $executables
      - $files-in-stage-packages
      - $freedesktop-desktop-entries
      - $manpages
      - $localizations
      - $pixmaps
      - $resources
